app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, index=True)
    #stored as a hash
    password = db.Column(db.String(100))
    watchlist = db.relationship('StockModel', backref='watcher', lazy='dynamic')

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

class StockModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ticker = db.Column(db.String(32), unique=True)
    company_name = db.Column(db.String(64))
    exchange = db.Column(db.String(64))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
login = LoginManager()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    login.init_app(app)
    migrate.init_app(app, db)

    from app.main import bp as main_bp
    from app.auth import bp as auth_bp
    from app.stock import bp as stock_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(stock_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template
from flask_login import current_user
from apihandler import IEXHandler

@bp.route('/')
def index():
    watchlist = ['AAPL', 'GOOG']
    handler = IEXHandler()
    # market_idx = ['DJI', 'SPY', 'NDAQ']
    # datasets = [handler.get_last_x_minute_data(idx, 60) for idx in market_idx]
    data = {
    'watchlist': watchlist
    }

    return render_template('main/logged_in_index.html', **data)

app/stock/__init__.py
from flask import Blueprint

bp = Blueprint('stock', __name__)

from app.stock import routes

app/stock/routes.py
from app.stock import bp
from app.models import StockModel
from iexfinance.stocks import Stock, get_historical_intraday
from flask import abort, flash, render_template, current_app, session
import requests
import json
import pandas as pd
from app import db
from datetime import datetime
from app.special import buttons, minute_data
from apihandler import IEXHandler, jsonminute
import time

@bp.route('/stock/<ticker>')
def stock(ticker):
    # start = time.time()
    # """
    # Four sources of information,
    # (1) A pandas dataframe with the intraday stock information (Useful for daily graphs)
    # (2) A iexfinance.stocks.Stock instance
    # (3) A pandas dataframe with yearly and daily information
    # (4) SQLAlchemy models instance of the ticker, if the ticker does not return a key error from IEX, create it in the database.
    # """
    # iex = IEXHandler()
    #
    # price = iex.get_current_price(ticker)
    # ticker_price_var = '{0}_price'.format(ticker)
    #
    # session[ticker_price_var] = price
    #
    # data15 = jsonminute(iex.get_last_x_minute_data, ticker, minutes=15)
    # data60 = jsonminute(iex.get_last_x_minute_data, ticker, minutes=60)
    # datatoday = jsonminute(iex.get_last_x_minute_data, ticker)
    # daily_return = round(iex.get_yesterdays_close_price(ticker)[1], 2)
    # ticker_change_var = '{0}_change'.format(ticker)
    #
    # session[ticker_change_var] = daily_return
    # end = time.time()
    # time_elapsed = round((end - start), 2)
    # flash("{0} seconds taken".format(time_elapsed))
    # kwargs = {
    # 'ticker': ticker, 'price': price, 'data15': data15, 'data60': data60, 'datatoday': datatoday,
    # 'sp_active': True, 'daily_return': round(daily_return, 2)
    # }

    kwargs = {'ticker': ticker}
    return render_template('stock/stock_price.html', **kwargs)

@bp.route('/stock/<ticker>/bs')
def bs(ticker):
    return render_template('stock/bs.html', ticker=ticker, bs_active=True)

@bp.route('/stock/<ticker>/is')
def income_st(ticker):
    iex = IEXHandler()
    return render_template('stock/is.html', ticker=ticker, is_active=True)

@bp.route('/stock/<ticker>/fr')
def fr(ticker):
    return render_template('stock/fr.html', ticker=ticker, fr_active=True)

@bp.route('/stock/<ticker>/kf')
def kf(ticker):
    return render_template('stock/kf.html', ticker=ticker,kf_active=True)

app/templates/base.html
<html lang="en">
<head>
  {% block head %}
<title>
  {% if title %} {{ title }} {% else %} Stocks {% endif %}
</title>

<link rel="shortcut icon" href="{{ url_for('static', filename='theme/favicon.ico')}}">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{{ url_for('static', filename='theme/assets/vendor/slick-carousel/slick/slick.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='theme/assets/vendor/font-awesome/css/fontawesome-all.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='theme//assets/vendor/hs-megamenu/src/hs.megamenu.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='theme/assets/vendor/chartist/dist/chartist.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='theme/assets/vendor/chartist-js-tooltip/chartist-plugin-tooltip.css')}}">
<!-- CSS Front Template, This always goes last -->
<link rel="stylesheet" href="{{ url_for('static', filename='theme/assets/css/theme.css')}}">

{% endblock head %}
</head>
{% block header %}
<header id="header" class="u-header">
  <div class="u-header__section">
    <div id="logoAndNavWithDropdown" class="container">
      <!-- Nav -->
      <nav class="js-mega-menu navbar navbar-expand-md u-header__navbar u-header__navbar--no-space">
        <!-- Logo -->
        <a class="navbar-brand u-header__navbar-brand u-header__navbar-brand-center" href="{{ url_for('main.index')}}" aria-label="Front">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="46px" height="46px" viewBox="0 0 46 46" xml:space="preserve" style="margin-bottom: 0;">
            <path fill="#3F7DE0" opacity=".65" d="M23,41L23,41c-9.9,0-18-8-18-18v0c0-9.9,8-18,18-18h11.3C38,5,41,8,41,11.7V23C41,32.9,32.9,41,23,41z"/>
            <path class="fill-info" opacity=".5" d="M28,35.9L28,35.9c-9.9,0-18-8-18-18v0c0-9.9,8-18,18-18l11.3,0C43,0,46,3,46,6.6V18C46,27.9,38,35.9,28,35.9z"/>
            <path class="fill-primary" opacity=".7" d="M18,46L18,46C8,46,0,38,0,28v0c0-9.9,8-18,18-18h11.3c3.7,0,6.6,3,6.6,6.6V28C35.9,38,27.9,46,18,46z"/>
            <path class="fill-white" d="M17.4,34V18.3h10.2v2.9h-6.4v3.4h4.8v2.9h-4.8V34H17.4z"/>
          </svg>
          <span class="u-header__navbar-brand-text">candlestick.io</span>
        </a>
        <!-- End Logo -->

        <!-- Responsive Toggle Button -->
        <button type="button" class="navbar-toggler btn u-hamburger"
                aria-label="Toggle navigation"
                aria-expanded="false"
                aria-controls="navBarWithDropdown"
                data-toggle="collapse"
                data-target="#navBarWithDropdown">
          <span id="hamburgerTriggerWithDropdown" class="u-hamburger__box">
            <span class="u-hamburger__inner"></span>
          </span>
        </button>
        <!-- End Responsive Toggle Button -->

        <!-- Navigation -->
        <div id="navBarWithDropdown" class="collapse navbar-collapse u-header__navbar-collapse">
          <ul class="navbar-nav u-header__navbar-nav">
            <!-- Link -->
            <li class="nav-item u-header__nav-item">
              <a class="nav-link u-header__nav-link" href="#">Markets</a>
            </li>
            <!-- End Link -->

            <!-- Link -->
            <li class="nav-item u-header__nav-item">
              <a class="nav-link u-header__nav-link" href="#">Industries</a>
            </li>
            <!-- End Link -->

           <!-- Dropdown -->
          <li class="nav-item hs-has-sub-menu u-header__nav-item"
              data-event="click"
              data-animation-in="slideInUp"
              data-animation-out="fadeOut">
            <a id="dropdownMegaMenuWithDropdown" class="nav-link u-header__nav-link u-header__nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="dropdownSubMenuWithDropdown">Watchlist</a>

            <!-- Dropdown - Submenu -->
            <ul id="dropdownSubMenuWithDropdown" class="hs-sub-menu u-header__sub-menu" aria-labelledby="dropdownMegaMenuWithDropdown" style="min-width: 230px;">
              {% if current_user.is_authenticated %}
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Action</a></li>
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Another action</a></li>
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Something else here</a></li>
              {% else %}
              {% for ticker in watchlist %}
              <li><a class="nav-link u-header__sub-menu-nav-link" href="{{ url_for('stock.stock', ticker=ticker)}}">{{ ticker }}</a></li>
              {% endfor %}
              {% endif %}
              <!-- End Submenu -->
            </ul>
            <!-- End Dropdown - Submenu -->
          </li>
          <!-- End Dropdown -->

            <!-- Button -->
            <li class="nav-item u-header__nav-last-item">
              <a class="btn btn-sm btn-primary transition-3d-hover" href="{{ url_for('auth.login') }}">
                Login
              </a>
            </li>
            <!-- End Button -->
          </ul>
        </div>
        <!-- End Navigation -->
      </nav>
      <!-- End Nav -->
    </div>
  </div>
</header>
{% endblock header %}
<body>
{% block content %}
<div class="container space">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info alert-dismissable fade-show" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
</div>
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}

        {% endblock %}
{% endblock content %}
</body>
{% block footer %}
<!-- ========== FOOTER ========== -->
<footer class="position-relative text-center mx-auto">
  <!-- Go To Top -->
  <a class="js-go-to" href="javascript:;"
     data-type="absolute"
     data-position='{
       "bottom": 86,
       "right": 0,
       "left": 0
     }'
     data-compensation="#header"
     data-show-effect="slideInUp"
     data-hide-effect="slideOutDown">

    <!-- SVG Wave Shape -->
    <figure class="u-go-to-wave ie-go-to-wave">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 208 44" style="margin-bottom: -32px; enable-background:new 0 0 208 44;" xml:space="preserve">
        <path class="fill-primary" d="M0,43c0,0,22.9,2.2,54-18.7S95.1,1.5,95.1,1.5s11.2-3.5,20.1,0.1s10.4,3.7,19.2,9.3c7.7,4.8,15,10.1,22.8,14.9
          c10.1,6.2,21.5,11.7,33,14.8C191.6,41,208,44,208,43c0,0,0,1,0,1H0V43z"/>
      </svg>

      <span class="fas fa-angle-double-up text-white u-go-to-wave__icon"></span>
    </figure>
    <!-- End SVG Wave Shape -->
  </a>
  <!-- End Go To Top -->

  <div class="bg-primary">
    <div class="container space-1">
      <p class="small text-white-70 mb-0">© Front. 2018 Htmlstream. All rights reserved.</p>
    </div>
  </div>
</footer>
<!-- ========== END FOOTER ========== -->
{% endblock footer %}
{% block scripts %}
<!--- JS Global Compulsory --------->
<script src="{{ url_for('static', filename='theme/assets/vendor/jquery/dist/jquery.min.js')}}"></script>
<script src="{{ url_for('static', filename='theme/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js')}}"></script>
<script src="{{ url_for('static', filename='theme/assets/vendor/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{ url_for('static', filename='theme/assets/vendor/bootstrap/bootstrap.min.js')}}"></script>
<!--- End JS Global --------------->

<!--- JS Implementing Plugins --------->
<!-- MegaMenu -->
<script src="{{ url_for('static', filename='theme/assets/vendor/hs-megamenu/src/hs.megamenu.js')}}"></script>
<!-- Chart JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
<script src="{{ url_for('static', filename='theme/assets/vendor/chartist/dist/chartist.min.js')}}"></script>
<script src="{{ url_for('static', filename='theme/assets/vendor/chartist-js-tooltip/chartist-plugin-tooltip.js')}}"></script>

<!--- End JS Plugins --------->

<!--- JS Front ------------>
<script type="text/javascript" src="{{ url_for('static', filename='theme/assets/js/hs.core.js')}}"></script>
  <!-- Header NAVBAR -->
<script type="text/javascript" src="{{ url_for('static', filename='theme/assets/js/components/hs.header.js')}}"></script>
  <!-- Unfold component -->
<script type = "text/javascript" src="{{ url_for('static', filename='theme/assets/js/components/hs.unfold.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='theme/assets/js/components/hs.go-to.js')}}"></script>
<script type = "text/javascript" src="{{ url_for('static', filename='theme/assets/js/components/hs.chartist-area-chart.js')}}"></script>
<!--- End JS Front ---------->

<!--JS Plugins Init ---------->
<script type="text/javascript">
  $(document).on('ready', function () {
    // initialization of header and navbar
    $.HSCore.components.HSHeader.init($('#header'));
    $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));
    $.HSCore.components.HSChartistAreaChart.init($('.js-area-chart'));
    // initialization of go to
    $.HSCore.components.HSGoTo.init('.js-go-to');
  });

  $(window).on('load', function () {
    // initialization of HSMegaMenu component
    $('.js-mega-menu').HSMegaMenu({
      event: 'click',
      pageContainer: $('.container'),
      breakpoint: 767.98,
      hideTimeOut: 0
    });
  });

</script>
{% endblock scripts %}
<!-- End JS Plugins Init -->
</html>

app/templates/base/content.html
<div class="container space-2">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info alert-dismissable fade-show" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}

        {% endblock %}
</div>

app/templates/base/footer.html
<footer class="bg-dark">
    <div class="border-bottom">
      <div class="row justify-content-lg-between mb-7">
        <div class="col-6 col-md-4 col-lg-2 mb-7 mb-lg-0">
          <h4 class="h6 text-white">About</h4>

          <!-- List Group -->
          <ul class="list-group list-group-transparent list-group-white list-group-flush list-group-borderless mb-0">
            <li><a class="list-group-item list-group-item-action" href="../pages/about-agency.html">About</a></li>
            <li><a class="list-group-item list-group-item-action" href="../pages/services-agency.html">Services</a></li>
            <li><a class="list-group-item list-group-item-action" href="../pages/careers.html">Careers</a></li>
          </ul>
          <!-- End List Group -->
        </div>

        <div class="col-6 col-md-4 col-lg-2 mb-7 mb-lg-0">
          <h4 class="h6 text-white">Account</h4>

          <!-- List Group -->
          <ul class="list-group list-group-transparent list-group-white list-group-flush list-group-borderless mb-0">
            <li><a class="list-group-item list-group-item-action" href="../account/dashboard.html">Account</a></li>
            <li><a class="list-group-item list-group-item-action" href="../account/my-tasks.html">My tasks</a></li>
            <li><a class="list-group-item list-group-item-action" href="../account/projects.html">Projects</a></li>
            <li><a class="list-group-item list-group-item-action" href="../account/invite-friends.html">Invite friends</a></li>
          </ul>
          <!-- End List Group -->
        </div>

        <div class="col-6 col-md-4 col-lg-2 mb-7 mb-lg-0">
          <h4 class="h6 text-white">Contacts</h4>

          <!-- Address -->
          <address class="list-group list-group-transparent list-group-white list-group-flush list-group-borderless mb-0">
            <a class="list-group-item list-group-item-action" href="#">+1 (062) 109-9222</a>
            <a class="list-group-item list-group-item-action" href="mailto:support@htmlstream.com">support@htmlstream.com</a>
            <a class="list-group-item list-group-item-action" href="#">153 Williamson Plaza, Maggieberg, MT 09514</a>
          </address>
          <!-- End Address -->
        </div>

        <div class="col-sm-6 col-md-5 col-lg-3 col-lg-3">
          <div class="mb-4">
            <h4 class="h6 text-white mb-3">Subscribe</h4>

            <!-- Subscribe Form -->
            <form class="js-validate js-form-message" novalidate="novalidate">
              <label class="sr-only" for="subscribeSrEmail">Your email</label>
              <div class="input-group">
                <input type="email" class="form-control" name="email" id="subscribeSrEmail" placeholder="Your email" aria-label="Your email" aria-describedby="subscribeButton" required="" data-msg="Please enter a valid email address.">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary" id="subscribeButton">
                    <span class="fas fa-paper-plane"></span>
                  </button>
                </div>
              </div>
            </form>
            <!-- End Subscribe Form -->
          </div>

          <h4 class="h6 text-white-70 mb-3">Stay in touch</h4>

          <!-- Social Networks -->
          <ul class="list-inline mb-0">
            <li class="list-inline-item">
              <a class="btn btn-sm btn-icon btn-soft-secondary" href="#">
                <span class="fab fa-facebook-f btn-icon__inner"></span>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-sm btn-icon btn-soft-secondary" href="#">
                <span class="fab fa-google btn-icon__inner"></span>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-sm btn-icon btn-soft-secondary" href="#">
                <span class="fab fa-twitter btn-icon__inner"></span>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-sm btn-icon btn-soft-secondary" href="#">
                <span class="fab fa-github btn-icon__inner"></span>
              </a>
            </li>
          </ul>
          <!-- End Social Networks -->
        </div>
      </div>

      <div class="row justify-content-between align-items-center space-1">
        <div class="col-5">
          <!-- Logo -->
          <a class="d-inline-flex align-items-center mb-3" href="../home/index.html" aria-label="Front">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="36px" height="36px" viewBox="0 0 46 46" xml:space="preserve" style="margin-bottom: 0;">
              <path fill="#E1E4EA" opacity=".65" d="M23,41.1L23,41.1c-9.9,0-18-8-18-18l0,0c0-9.9,8-18,18-18h11.3c3.7,0,6.6,3,6.6,6.6v11.4C41,33,32.9,41.1,23,41.1z"></path>
              <path class="fill-white" opacity=".5" d="M28,36L28,36c-9.9,0-18-8-18-18l0,0c0-9.9,8-18,18-18h11.3C43,0.1,46,3.1,46,6.7v11.4C46,28,38,36,28,36z"></path>
              <path class="fill-white" opacity=".7" d="M18,46.1L18,46.1c-10,0-18-8-18-18l0,0c0-9.9,8-18,18-18h11.3c3.7,0,6.6,3,6.6,6.6v11.4C35.9,38.1,27.9,46.1,18,46.1z"></path>
              <path class="fill-primary" d="M17.4,34.1V18.4h10.2v2.9h-6.4v3.4H26v2.9h-4.8v6.5H17.4z"></path>
            </svg>
            <span class="brand brand-light">Front</span>
          </a>
          <!-- End Logo -->
        </div>

        <div class="col-6 text-right">
          <p class="small mb-0">Candlestick. 2019.</p>
        </div>
      </div>
    </div>
  </footer>

app/templates/base/navbar.html
<header id="header" class="u-header">
  <div class="u-header__section">
    <div id="logoAndNavWithDropdown" class="container">
      <!-- Nav -->
      <nav class="js-mega-menu navbar navbar-expand-md u-header__navbar u-header__navbar--no-space">
        <!-- Logo -->
        <a class="navbar-brand u-header__navbar-brand u-header__navbar-brand-center" href="{{ url_for('main.index')}}" aria-label="Front">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="46px" height="46px" viewBox="0 0 46 46" xml:space="preserve" style="margin-bottom: 0;">
            <path fill="#3F7DE0" opacity=".65" d="M23,41L23,41c-9.9,0-18-8-18-18v0c0-9.9,8-18,18-18h11.3C38,5,41,8,41,11.7V23C41,32.9,32.9,41,23,41z"/>
            <path class="fill-info" opacity=".5" d="M28,35.9L28,35.9c-9.9,0-18-8-18-18v0c0-9.9,8-18,18-18l11.3,0C43,0,46,3,46,6.6V18C46,27.9,38,35.9,28,35.9z"/>
            <path class="fill-primary" opacity=".7" d="M18,46L18,46C8,46,0,38,0,28v0c0-9.9,8-18,18-18h11.3c3.7,0,6.6,3,6.6,6.6V28C35.9,38,27.9,46,18,46z"/>
            <path class="fill-white" d="M17.4,34V18.3h10.2v2.9h-6.4v3.4h4.8v2.9h-4.8V34H17.4z"/>
          </svg>
          <span class="u-header__navbar-brand-text">candlestick.io</span>
        </a>
        <!-- End Logo -->

        <!-- Responsive Toggle Button -->
        <button type="button" class="navbar-toggler btn u-hamburger"
                aria-label="Toggle navigation"
                aria-expanded="false"
                aria-controls="navBarWithDropdown"
                data-toggle="collapse"
                data-target="#navBarWithDropdown">
          <span id="hamburgerTriggerWithDropdown" class="u-hamburger__box">
            <span class="u-hamburger__inner"></span>
          </span>
        </button>
        <!-- End Responsive Toggle Button -->

        <!-- Navigation -->
        <div id="navBarWithDropdown" class="collapse navbar-collapse u-header__navbar-collapse">
          <ul class="navbar-nav u-header__navbar-nav">
            <!-- Link -->
            <li class="nav-item u-header__nav-item">
              <a class="nav-link u-header__nav-link" href="#">Markets</a>
            </li>
            <!-- End Link -->

            <!-- Link -->
            <li class="nav-item u-header__nav-item">
              <a class="nav-link u-header__nav-link" href="#">Industries</a>
            </li>
            <!-- End Link -->

           <!-- Dropdown -->
          <li class="nav-item hs-has-sub-menu u-header__nav-item"
              data-event="click"
              data-animation-in="slideInUp"
              data-animation-out="fadeOut">
            <a id="dropdownMegaMenuWithDropdown" class="nav-link u-header__nav-link u-header__nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="dropdownSubMenuWithDropdown">Watchlist</a>

            <!-- Dropdown - Submenu -->
            <ul id="dropdownSubMenuWithDropdown" class="hs-sub-menu u-header__sub-menu" aria-labelledby="dropdownMegaMenuWithDropdown" style="min-width: 230px;">
              {% if current_user.is_authenticated %}
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Action</a></li>
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Another action</a></li>
              <li><a class="nav-link u-header__sub-menu-nav-link" href="#">Something else here</a></li>
              {% else %}
              {% for ticker in watchlist %}
              <li><a class="nav-link u-header__sub-menu-nav-link" href="{{ url_for('stock.stock', ticker=ticker)}}">{{ ticker }}</a></li>
              {% endfor %}
              {% endif %}
              <!-- End Submenu -->
            </ul>
            <!-- End Dropdown - Submenu -->
          </li>
          <!-- End Dropdown -->

            <!-- Button -->
            <li class="nav-item u-header__nav-last-item">
              <a class="btn btn-sm btn-primary transition-3d-hover" href="{{ url_for('auth.login') }}">
                Login
              </a>
            </li>
            <!-- End Button -->
          </ul>
        </div>
        <!-- End Navigation -->
      </nav>
      <!-- End Nav -->
    </div>
  </div>
</header>

app/templates/main/logged_in_index.html
{% extends "base.html" %}
{% block content %}
<main id="content" role="main">
<div class="container space-2">
{% include "main/markets.html" %}
</div>
</main>
{% endblock content %}
{% block scripts %}
{{ super() }}
<script>
</script>
{% endblock %}

app/templates/main/markets.html
<div class="row justify-content-lg-between align-items-md-start">
  <div class="col-md-4 mb-5">
    <p>DJIA</p>
    <canvas id="DJIA">DJIA</canvas>
  </div>
  <div class="col-md-4 mb-5">
    <p>S&P500</p>
    <canvas id="SP">S&P500</canvas>
  </div>
  <div class="col-md-4 mb-5">
    <p>NASDAQ</p>
    <canvas id="NASDAQ">NASDAQ</canvas>
  </div>
</div>

app/templates/stock/bs.html
{% extends "stock/stock.html" %}
{% block stock_content %}
{% endblock %}